name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Hello world
      id: hello-world
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: pip install numpy, matplotlib, scipy, sympy
    - name: Hello world2
      id: hello-world2
      uses: education/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: pip install pytest numpy matplotlib scipy sympy
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        HELLO-WORLD_RESULTS: "${{steps.hello-world.outputs.result}}"
        HELLO-WORLD2_RESULTS: "${{steps.hello-world2.outputs.result}}"
      with:
        runners: hello-world,hello-world2
